### ISSUE TITLE
S3 - Group Feed "Conversation View"

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#116]
The ability for the group owner to set the "default view" for the group feed. Currently, the frontend displays group content in only one format - we'll call that the 'Feed View' format. However, for groups less than 10 people, the view would default to a "Conversation View" format, which is designed more for the initial needs of a small team just starting as opposed to a large team.

The only backend work required for this is a small switch that the group owner can change. The system should default to Conversation View for groups less than 10 people. It should change to Feed View for groups greater than 10 people. The group owner should be able to change it any time. 

The frontend work is fairly simple. It will check the switch to determine which view should be used. Conversation View mimics a chat window with multiple participants. A user avatar and name appear with the body of the message. There are no upvote/downvote/reply buttons or comment previews. There is no bordered 'container' per se. The user is not given the ability to reply to a post. All the "extras" are not displayed in Conversation View - it just looks like a simple chat window. Obviously this would only impact the selected Group Feed (not the All Feed) and the user would only see the Conversation View when they go to the Group Selector on the main screen, select the More button, and select the group. 

User A is part of Hoboken, New Jersey, USA, Save the Whales, and Save the Trees groups... Save the Whales has 9 users. Save the Trees has 3000 users. User B is the owner of Save the Whales and Save the Trees... User A views his All feed and it looks like the normal newsfeed (standard item container). He sees the Feed view. Then, User A opens the USA group feed from the Group Selector and it looks like the normal newsfeed (standard item container). It is also the Feed view. Then, User A opens the Save the Whales group from the Group Selector and because it has less than 10 members, the app shows the Conversation View for the Save the Whales group. In the Conversation view, the UI looks looks very similar to how root comments display on the Item Detail Screen, except there is no upvote, downvote, or reply buttons. It simply shows an avatar and a name along with each post - it looks like a group chat in any chat application. Very simple. Tapping on any item will open the Standard Item Detail screen for that item.... When User A looks at the Save the Trees group, it is in normal Feed view (because it has over 10 group members).... User B can go to the Manage Group screen and manually change the default view from Conversation view to Feed view (and vice versa) at any time. The normal group member does not have the ability to switch views manually.

**Comment by jterps08** [comment]
rough mockup below
![image](https://user-images.githubusercontent.com/7582457/28645209-a987af76-722a-11e7-96e0-829a8f83b734.png)

**Comment by jterps08** [comment]
@igaponov can you let @thiago-19960626 where this information is in the json response? I think 

@thiago-19960626 per the description above, when the user selects the group feed from the group selector, the app should already have the 'default view' information from the group list json response so that it does not need to make a second api request. It can then _quickly_ display the correct view based on what the default view is set to on the backend... For now, I think you can work on this without knowing exactly what the possible json response will be... but Igor and you can work together in Slack to discuss.

We will add the ability for the group owner to change the default view to the Manage Group screen at a later time.

**Comment by igaponov** [comment]
@jterps08 Do you want to show group's posts in this view? How many of them? And this information should be in the groups response? We don't have it in there now and this will slow down the groups endpoint.

**Comment by jterps08** [comment]
@igaponov I don't believe any changes are needed for group posts endpoint. Will discuss on Slack. The only thing we need is an indicator in the json response for the groups list that tells us what the default view is... Will explain in Slack

**Comment by jterps08** [comment]
The Conversation View (#116) is a different way of displaying the information we already provide for the Group Feed (#45)... Here's how it works... 1) the user is on the home screen, 2) the user selects the More button to open the Group Selector, 2a) the backend provides a list of groups somehow to the frontend for this screen. it should now include an indicator as to whether or not the default view for each group is conversation view or feed view, 3) user selects a feed to open (e.g. Save the Whales) and the app already has the information as to whether or not it is displaying STW posts in conversation view or feed view... 3a) for the sake of this example, let's say that STW is in conversation view, 4) the frontend requests the group feed as usual but displays it in the conversation view instead of the normal feed view...

See difference below: 

![image](https://user-images.githubusercontent.com/7582457/29169823-011aa03e-7da4-11e7-8ba7-e608e4ba3d67.png)

**Comment by igaponov** [comment]
Then use `total_members` attribute from json response to determine a view type.

**Comment by jterps08** [comment]
Yes, but we want to give the group leader the ability to change the default
view type for their group. For example, if the default number is 10 and
there are 15 group members, the group member may want to change the default
view anyway to Conversation View... Open to different approaches if you
have any alternative ideas?

**Comment by igaponov** [comment]
Ten only have to add that option to group's table on backend.

**Comment by jterps08** [comment]
Perfect

**Comment by jterps08** [comment]
@thiago-19960626 Igor has added this to backend, please ask him for any questions regarding above commit

**Comment by jterps08** [comment]
This is buggy. It can only be fixed after normal Group Feed view is fixed (dependent on Newsfeed stability / Activities.js stability)... 

Once those are stable, Conversation View only activates if group member count is < Conversation View Limit (currently set to 10 on backend). Think of Conversation View as "Group Chat UI" for a Group instead of Newsfeed UI. Designed to make small group activity more personal.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/21/17 - 10/26/17
Work session total: 2:52:26

Grand total: 2:52:26
