### ISSUE TITLE
S5 - Elected Leader Registration Form

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#117]
https://github.com/PowerlineApp/powerline-mobile/issues/593

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#post--api-v2-user-representatives

**Comment by matheusrezende** [comment]
via Hubstaff
User: Matheus Rezende Figueira

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/15/17 - 11/17/17
Work session total: 8:03:10

Grand total: 8:03:10
