### ISSUE TITLE
S5 - New Leader Content Forms

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#118]
For polls, fundraisers, events, petitions, discussions, and announcements. (leader content)

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/29/17 - 11/12/17
Work session total: 11:36:08

Grand total: 11:36:08
