### ISSUE TITLE
Sprint 3 Fix - Entering Comment, Active Keyboard

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#132]
When user taps Reply button or "Add Comment" button, the Comment Entry screen should appear with the keyboard already extended. Enough white text entry space for 2-3 lines of text should be present. Placeholder text is also missing.

**Comment by jterps08** [comment]
assigning to Matheus as basic RN PL frontend work (after #166)

**Comment by jterps08** [comment]
@piubellofelipe 

On iOS: Tapping Reply button from Newsfeed *or* Item Detail Screen does not open the Comment Entry screen as expected with keyboard extended... Tapping Add Comment *does* open the Comment Entry Screen as expected with keyboard extended... However, text is not wrapping as expected. 
Android: Not yet tested.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/11/17 - 10/17/17
Work session total: 0:55:37

Grand total: 0:55:37
