### ISSUE TITLE
Notify Friends About Post

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#137]
User has the ability to notify their followers (with push notification) about someone else's post on an occasional basis (e.g. can only do it to one post every 3 days)... User A creates post in Group 1 His follower User B is also in Group 1 and upvotes User A's post. User B 'shares' the post with his followers Users C/D/E/F who get a push notification. Only User C/D/E are in Group 1 so they receive push notification. User F is not in Group 1 so they do not receive notification. User B can't share any post for another 1 hours. User B can only notify friends about a post if he has upvoted the post himself first.

The notification title is FirstNameSharer LastNameSharer. The notification message is "shared [firstNameAuthor]'s post with you: [textByAuthor]"...

For example:
title: Joe Smith
message: shared Jesse's post with you: "This is the body of Jesse's post that Joe is sharing with you..."
avatar: Joe Smith

**Frontend:**
On both Standard Item Container drop-down menu *and* the Item Detail Screen drop-down menu, an option appears entitled "Share this post to followers". The user selects it. A pop-up alert says "Instantly notify all of your followers in this group about this post? You can only do this once every hour." Yes/No.

The option only appears if:
a) the User has upvoted the post
b) the User has not shared a post in the last 1 hours <- There is a backend switch for this one hour timer. We should error-handle the backend response if user tries to do it again less than one hour.

![image](https://user-images.githubusercontent.com/7582457/31474568-a5f1aad4-aec9-11e7-85d8-11dc7b26ea81.png)

**Comment by igaponov** [comment]
@jterps08 can a user share the same post several times?

**Comment by jterps08** [comment]
Good question. Let's say yes. We may want to change these rules in the future, but here's how I imagine it:
a) the user has upvoted the specific post
b) the user has not shared *any* post in the last 72 hours
c) the user may share the specific post again, but only after 72 hour period has passed.

The accompanying push notification should have the Upvote / Reply buttons, which I can add to the Google Doc.

**Comment by jterps08** [comment]
@igaponov can you provide the API endpoint here please

**Comment by jterps08** [comment]
@igaponov I'd also like to include upvote downvote buttons on this, too

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#put--api-v2-user-shared-posts-{id}
