### ISSUE TITLE
Rapid Registration

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#139]
System should be able to support a registration flow where user creates account (manually or with FB) and the only address information that s/he provides is country and zip code OR potentially no zip code at all. This flow encourages rapid entry into the app, but, as a result, we must make effort to get accurate information after registration.

This will involve three points:
1) Allow registration with or without zipcode/address information (with error handling)
2) Introduce a Percent Complete concept for the User's Profile (mostly frontend)
3) From #214, the SMS code provision and verification. 
 
The scope of this effort for @igaponov is #1 and #3... We can add verification badge programmatically using Imgix but I am open to other options.

Here's how it will work:

**During initial user registration flow:**
User taps manual registration button and provides Account Setup (name, email, username, password) OR user taps Facebook registration button... Currently, the system asks for the user's full address after account setup/FB registration. Instead, we will now ask for user's zip code and country only (plus e-mail on that screen)

![image](https://user-images.githubusercontent.com/7582457/32205297-d7e7d09a-bdc4-11e7-9686-0fb5c800e14d.png)

UI will provide a small modal "Where do you live?" message with placeholder text (10004). User presses Register button. If no zip code is provided, the Done button will still work but user must provide country. Country is preferably pre-filled by app based on device. User should be linked to town/state/country groups and elected leaders as best as possible given zipcode/country combination. If the zip code returns only one possible town (e.g. 07030 - Hoboken), then the user is asked "Do you live in Hoboken?" Yes/No. If no, user returned to zip code screen. If yes, user completes the user's registration. If the zip code returns 2 or more possible towns (e.g. 07712 - Ocean, Asbury, Tinton Falls), then the user is asked to select the correct town. "Where do you live? Select the correct town." If more than one possible town, I think this can be handled completely by frontend with help of Google Maps API.

Appropriate town/state/country and zip code are stored in user profile. Linkages to elected leaders and town/state/country groups occurs. With zip code, user will be connected to all possible elected leaders from Cicero and town/state/country groups based on zip code. User is brought through welcome screens.

Above is 139. 

Flow: Login Screen -> Account Setup (manual/FB) -> Zip Code -> Welcome Screens -> Home Screen -> Verification Modal 

**After user registration** - This is #214

Once the user is registered and has clicked through the tour Welcome screens, the user receives a pop-up after a couple seconds...
User is presented with a pop-up: Title "Verify now?" Subtitle "Your profile is only 50% complete." "Earn your verification badge!" Verify/Later are the buttons. User taps Verify button. If user taps later, alert appears in 48 hours when user opens home screen again.
User is asked for address. "Let's link you to the correct elected leaders and public groups. This information will only be shared with those you choose to share it with." This screen is the same as the current 'full' version of the registration screen.  Next.
User provides address. Google-assisted address form. Bottom of form says "We may occasionally contact you via e-mail, but we will never sell your information."
User's elected leaders and town/state/country groups are updated. 
NEW:  Screen 2 asks for mobile number (keypad should appear on focus). User should be able to provide mobile number (including country code) for system to send SMS code for verification within 30 minutes. User should be able provide SMS code back for verification. 

If user adds address **and** adds mobile number successfully, user should be isVerified=true.
User is presented with a pop-up: "If successful, user receives note "Great - you're verified!" and show the user's avatar with the blue verification checkmark overlaid. 

Everywhere user's avatar appears (newsfeed, item detail screen, my influences, comments), the blue verification checkmark watermark appears if user isVerified=true.

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#post--api-v2-security-login
https://api-dev.powerli.ne/api-doc#post--api-v2-security-registration

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/20/17 - 11/22/17
Work session total: 7:29:28

Grand total: 7:29:28
