### ISSUE TITLE
Sprint 3 Fix - Unable to Join Groups

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#147]
User opens Group Profile Screen from Group Search. 
When tapping on "Join" button from Group Profile screen, user is not joined to group.

When tapping on + sign button from Group Search Results screen, user should be joined to group. Tappable area should be large enough. 

Group Join Screen needs to be setup.

**Comment by jterps08** [comment]
Different scenarios:
**Open Group** - User taps join button, shown group permissions alert, accepts, joined to group.
**Passcode Protected Group** - User taps join button, shown Group Join Screen with Passcode entry field, user enters correct passcode, shown group permissions alert, accepts, joined to group
**Manual Review Group** - 

All Scenarios:
**Group Permissions Alert** - User must see required permissions and agree before join is sent. 

Optional:
**Required Fields** - Group owner may setup additional fields for users to fill out when joining a group. If these

**Comment by matheusrezende** [comment]
via Hubstaff
User: Matheus Rezende Figueira

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/19/17 - 10/28/17
Work session total: 7:32:27

Grand total: 7:32:27
