### ISSUE TITLE
Manual Boost Post (for Leaders)

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#149]
Group Leaders (Group Owners and Group Managers) should be able to manually 'boost' a user **post** or **user petition** via the drop-down menu on the Newsfeed Standard Item Container or Item Detail Screen. Only available for posts/petitions in the group that the user is a leader in. Displays warning alert "All X group members will get a notification about this item immediately. Are you sure? Use sparingly!" Yes/No where X is the number of group members in that group. 

User A creates post in Group 1 
User B is a leader in Group 2. User B cannot boost User A's post in Group 1. Option does not appear on menu.
User C is a leader in Group 1. User C can boost User A's post in Group 1. Option appears on menu.

"Option" = "Boost this post to group"
"Leader" = group owner or group manager.

![image](https://user-images.githubusercontent.com/7582457/31474724-969e6562-aeca-11e7-9a69-9506c46228bb.png)

**Comment by mobileDevNativeCross** [comment]
How to check if I user is group manager?

**Comment by mobileDevNativeCross** [comment]
Should I hide boost option if its boosted already?

**Comment by jterps08** [comment]
@igaponov can answer regarding how to check if group manager

Yes, you should hide the boost option if its boosted already!

**Comment by mobileDevNativeCross** [comment]
@igaponov it would be nice to have it in activities like owner.
