### ISSUE TITLE
2b - App Store Readiness - Sign Button should work

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#152]
UserA creates a user petition. 
User be sees petition in newsfeed or in Item Detail Screen. 
User taps "Sign" button. 
Sign button does not work. 

Sign button for user-petitions / leader-petitions should actually sign the petition in newsfeed or in Item Detail Screen.

![image](https://user-images.githubusercontent.com/7582457/31479053-c68e38f2-aee2-11e7-976d-4e99361fe62a.png)

Sign / Unsign endpoints for **User** petition
https://api-dev.powerli.ne/api-doc#post--api-v2-user-petitions-{id}-sign
https://api-dev.powerli.ne/api-doc#delete--api-v2-user-petitions-{id}-sign

@igaponov please provide sign / unsign endpoints for **leader** petition

**Comment by igaponov** [comment]
Leader petition is a kind of poll, so it's possible only to answer it (but answer's options will be sign/unsing): https://api-dev.powerli.ne/api-doc#put--api-v2-polls-{id}-answers-{option}
There is no new endpoint to delete your answer, but we have the old one: https://api-dev.powerli.ne/api-doc#delete--api-petition-{id}-answers-{answerId}
@jterps08 should we add a new one to delete an answer?

**Comment by jterps08** [comment]
@igaponov yes, we should

**Comment by jterps08** [comment]
@igaponov yes, i think we need a new one. What is level of effort?

If frontend can use existing endpoint now, then frontend should proceed with existing endpoint and change when we update the endpoint

**Comment by igaponov** [comment]
@jterps08 it's relatively easy and fast

**Comment by jterps08** [comment]
Let's do it @igaponov - we'll file this under dev stability
