### ISSUE TITLE
2b - App Store Readiness - Town/State/Country Buttons Need Real Names

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#153]
Currently, the user sees "Town" "State" and "Country" buttons on the Group Selector on Home Screen. These should actually display real names or abbreviations. For example, Hoboken, NJ, USA. 

Town State Country buttons should be labeled with actual names

![image](https://user-images.githubusercontent.com/7582457/31304296-a97f62bc-aaec-11e7-934d-d94c59ddf45e.png)

**Comment by mobileDevNativeCross** [comment]
How can I filter it? I don't see here https://api-dev.powerli.ne/api-doc#get--api-v2-activities filter by town, state or country name or type.

**Comment by igaponov** [comment]
@mobileDevNativeCross town, state and country are groups with according names (for example a group with name "US"), you can filter by "group" query parameter.
