### ISSUE TITLE
2b - App Store Readiness - Friends Feed

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#154]
User is following zxc2 and abc, but user is seeing posts by people he does not follow in Friends Feed

@igaponov - For "Posts by Friends" feed, please give example API call. 
https://api-dev.powerli.ne/api-doc#get--api-v2-activities
Use followed=true|false, non_followed=true|false to filter followed users (don't use anything to filter all users). 

https://github.com/PowerlineApp/powerline-rn/blob/78be16af291ac829178aafc32e7af6647021480e/src/actions/activities.js#L5 

https://github.com/PowerlineApp/powerline-rn/blob/1c233fc71613bbb6050770308d1118a84e52733f/src/scenes/dashboard/friendsfeed/activities/index.js#L95

![image](https://user-images.githubusercontent.com/7582457/31303680-cb226d90-aadf-11e7-8ff5-5eb2b8848c31.png)

**Comment by igaponov** [comment]
Use followed=true for that

**Comment by jterps08** [comment]
OK cool so this is only a minor parameter adjustment to the request. Thanks.
