### ISSUE TITLE
2b - App Store Readiness - Larger Tappable Area for Upvoting/Downvoting Comments

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#159]
User should be able to easily upvote or downvote a comment (and change their vote!). Tappable area is pretty small right now. Needs to be easier to upvote/downvote a comment.

Maybe best accomplished by spacing out more? 
![image](https://user-images.githubusercontent.com/7582457/31479199-9ec2cf44-aee3-11e7-94da-f731c6e54701.png)

**Comment by jterps08** [comment]
iOS: done
Android: Not yet tested.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/12/17 - 10/12/17
Work session total: 0:11:21

Grand total: 0:11:21
