### ISSUE TITLE
S1 - Push Notifications - General

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#16]
User should be registered for push notifications after registration (manual or Facebook)
User should be registered for push notifications after login
User should be unregistered for push notifications after logout

The push notification alert should display two images (Large, small). The large icon is the group/user avatar. The small icon is the Powerline logo. 

User should receive push notification alerts in the following circumstances (reference columns A-K) here: https://docs.google.com/spreadsheets/d/1LtGkOehCA0th9Bk_tYTXWHC24NoifDC-E1iWkeyqjrY/edit?usp=sharing)

Rows 6, 7, 12, and 14 of the spreadsheet can be tested in Sprint 1.

**Comment by jterps08** [comment]
All items in Google Sheet will need to be finished before we can close this item. We will need to come back to this item when we address Leader Basics.

**Comment by jterps08** [comment]
This item is still open. Previous developer did not finish work as expected:
1) Push notification action buttons, 
2) routing when opening a notification, 
3) small P icon, 
4) search results doesn't work from home screen.

**Comment by thiago-19960626** [comment]
Hi Jesse, what is wrong on slack?
I cannot respond because I was outside.

**Comment by jterps08** [comment]
User jtest1 is logged into iOS
user abc1 is logged into Android

Why are they unsubscribed from notifications?

![image](https://user-images.githubusercontent.com/7582457/31924588-9fdff944-b850-11e7-9100-245befbf15b4.png)

**Comment by jterps08** [comment]
Marking this as closed. Still need to do exhaustive notification test on Android

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/12/17 - 11/09/17
Work session total: 15:57:16

Grand total: 15:57:16
