### ISSUE TITLE
Repo Stability

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#166]
The powerline-rn repo needs to be stable enough for any developer to clone to local and be able to compile a working build in Android and iOS simulator. This excludes functional and design bugs/issues otherwise acknowledged.

**Comment by jterps08** [comment]
This has multiple parts:
1) Feature Consolidation - Consolidate all the work from Felipe and Greg onto one branch. 
2a) Build Fix Merge Conflicts - Difference between Matheus' work and Greg's work on repo stability (ability to clone to local, run app in Android/iOS simulator, compile to IPA/APK) needs to be resolved. 
2b) Newsfeed Consolidation - We need to centralize the newsfeed functions (e.g. _renderFooter) into one place. The newsfeed code should exist in one place and referenced to as described in Slack. 

Matheus and Greg need to work together on this.

**Comment by matheusrezende** [comment]
via Hubstaff
User: Matheus Rezende Figueira

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/10/17 - 10/19/17
Work session total: 4:09:39

Grand total: 4:09:39
