### ISSUE TITLE
2b - App Store Readiness - Dropdown Menu: Follow this item's Author

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#173]
Add "Follow this item's author" to the dropdown menus on the Standard Item Container and on the Item Detail Screen. Sends a follow request to the author of the item. 

User A is logged in.
User B creates a post.
User A hits dropdown menu on User B's post. 
User A Selects "Follow this person"
Follow request from User A sent to User B.

*Part Two*
User B approves follow request
User A hits dropdown menu on User b's post.
Option appears as "Unfollow this person"

![image](https://user-images.githubusercontent.com/7582457/31475174-58babb08-aecd-11e7-9e24-98e865d808f1.png)

**Comment by mobileDevNativeCross** [comment]
@igaponov @jterps08 I think it would be better to have inside activity information about is this author is followed or not? What do you think about it?

**Comment by mobileDevNativeCross** [comment]
@jterps08 Also can you provide icons for options from ionicons?
