### ISSUE TITLE
Allow Users to Add Photo to a Post / User-Petition

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#182]
User has the ability to attach/upload a photo to a post or user petition. 

Frontend will have ability to upload photo during New Post / New User form. 
Frontend will show indicator in newsfeed Standard Item Container if photo attached to item. 
User will be able to swipe right-to-left on a Standard Item Container that has attachment, which will show attached image. User can swipe left-to-right to return to newsfeed.

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#post--api-v2.2-groups-{group}-posts
https://api-dev.powerli.ne/api-doc#post--api-v2.2-groups-{group}-user-petitions
`image` parameter

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/29/17 - 10/30/17
Work session total: 1:36:57

Grand total: 1:36:57
