### ISSUE TITLE
Critical - Newsfeed Consolidation Refactoring

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#187]
The same functions (e.g. _renderFooter) that support Newsfeed/FriendsFeed/ProfileFeed exist in 4 places and should only exist in one. When we make a change to the newsfeed (such as issue 13), it should only need to be made once and the change will appear every place a feed is displayed (e.g. Newsfeed, Group Feed, Friends Feed, User Feed, etc.). Again, only difference between these feeds are the parameters sent to the API. Otherwise, JSON response format is identical in each case.

Newsfeed uses X
Friendsfeed uses X
Groupfeed uses X
User Profile Feed uses X

X = the same set of functions/views/etc. The only difference between each case is the parameter sent to the backend API.

**Comment by jterps08** [comment]
Note: It is possible that #154 (Friends Feed) and #157 (User Profile Feed) and #116 issues were resolved  as a result of Felipe's work on 187... However, #142 (Conversation View) is not expected to have been fixed as a result of newsfeed consolidation. 

I will test this when I have a build for this item.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/16/17 - 10/17/17
Work session total: 4:08:24

Grand total: 4:08:24
