### ISSUE TITLE
Critical - Tapping Item in Newsfeed Opens Wrong Item Detail Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#193]
User taps on user petition item in Newsfeed "Simple petition"
![image](https://user-images.githubusercontent.com/7582457/31731986-df5ff5b0-b404-11e7-812a-7a49fb14f886.png)

Item Detail screen opens for "Another" user petition instead - should open correct item.
![image](https://user-images.githubusercontent.com/7582457/31731993-e2f6f7a0-b404-11e7-9a5a-fd284676cc75.png)

**Comment by piubellofelipe** [comment]
@igaponov , I believe it's an API problem, with the endpoint /v2/activities
I fetched from  '/v2/activities?_format=json&user-petition_id=347 , the endpoint returned me the wrong object

**Comment by igaponov** [comment]
@piubellofelipe can we close it?
