### ISSUE TITLE
S1 - Item Detail Screen - Petitions

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#21]
Linked to #19. You will approximate this UI based on the Posts Item Detail Screen.

Petitions display a title in addition to regular body text. Petitions can be signed and unsigned. When a petition is signed, the button changes to "Unsign". There is no upvote or downvote button on a petition.

![item-detail-v2](https://cloud.githubusercontent.com/assets/7582457/26016858/bf116980-3734-11e7-88ce-13ee28f79c33.png)

**Comment by jterps08** [comment]
Marking an item as read: When user opens group petition, group discussion -> https://api-dev.powerli.ne/api-doc#patch--api-v2-activities... When user answers poll/fundraiser/event -> https://api-dev.powerli.ne/api-doc#patch--api-v2-activities... When user opens boosted post/userpetition, ->https://api-dev.powerli.ne/api-doc#patch--api-v2-activities

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/14/17 - 11/14/17
Work session total: 1:10:02

Grand total: 1:10:02
