### ISSUE TITLE
Release A - Critical Bug - Priority Zone Counter Not Working

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#226]
![image](https://user-images.githubusercontent.com/7582457/32202607-4c9189a6-bdb4-11e7-9d22-a3eb845364b1.png)

I am logged in as abc and yet two of my items are in the priority zone. I should be able to either sign or view to remove from priority zone. @igaponov please advise. Given two items have the lightning symbol, I would expect to see a "2" badge near the Newsfeed icon.

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-v2-user-statistics
