### ISSUE TITLE
Release A - Critical Bug - Posts Remaining Counter

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#229]
![image](https://user-images.githubusercontent.com/7582457/32202714-eae3808c-bdb4-11e7-873b-d50a15e0fe6f.png)

Why does this say -5? If user has 0 remaining, s/he should not be allowed to create item in that group.

**Comment by igaponov** [comment]
``` bash
$ http GET https://api-dev.powerli.ne/api/v2/groups/1/micro-petitions-config "Token: $ABC_TOKEN" 
HTTP/1.1 200 OK
...

{
    "petition_duration": null, 
    "petition_per_month": 5, 
    "petition_percent": null, 
    "petitions_remaining": 5, 
    "posts_remaining": 5
}
```

**Comment by piubellofelipe** [comment]
this is a frontend problem. how should the app handle it? make the "send" button and the textinput not working when the user exceeded his posts/petition ?

**Comment by jterps08** [comment]
@piubellofelipe Just make the send button create an alert "You've exceeded the number of allowed posts this month in this group." In the future, we may allow user to upgrade to bypass limits or only allow Verified users to bypass limits.

**Comment by piubellofelipe** [comment]
ok, I'll make the fix. thanks
