### ISSUE TITLE
Release A - Critical Bug - User Profile Screen Town/Country

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#238]
![image](https://user-images.githubusercontent.com/7582457/32203911-9ff59710-bdbc-11e7-9f0a-7cdb34323a1c.png)

This looks hardcoded the same for all users. Please investigate. Should come from backend.

**Comment by piubellofelipe** [comment]
![image](https://user-images.githubusercontent.com/18724958/32220691-d2f5117e-be19-11e7-89cd-076614e0e3d5.png)
It seems to be working fine for me. I will do further investigation

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/31/17 - 10/31/17
Work session total: 0:03:04

Grand total: 0:03:04
