### ISSUE TITLE
Release A - Critical Bug - Hide Share Button on Private Group Items

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#240]
Share button should only appear on Item Detail Screen for items in *public groups* (e.g. town/state/country). If this is not easily possible with current JSON response, then only show if user is author of the post for release A and assign backend work to Igor as needed. 

![image](https://user-images.githubusercontent.com/7582457/32204126-dad7f2e6-bdbd-11e7-9d1a-2fec1ae9e88d.png)

**Comment by piubellofelipe** [comment]
is verifying if "group_type_label" is "local", "state" or "country" enough for displaying the share button, or there are more types of group?
the current JSON type I receive is:
```
group:
{ type: 'group',
avatar_file_path: 'https://powerline-dev.imgix.net/avatars/src/59bbd398e3f7e948409717.png?ixlib=php-1.1.0',
banner: null,
group_type_label: 'local',
user_role: 'member',
id: 422,
official_name: 'Elizabeth' },
```

**Comment by jterps08** [comment]
@piubellofelipe yes. if its local state or country, it's enough.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/31/17 - 10/31/17
Work session total: 0:13:15

Grand total: 0:13:15
