### ISSUE TITLE
Release A - Critical Bug - Total Member Count Wrong

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#242]
There are two members to this group as shown on the Membership screen... but the count says 1. 

![image](https://user-images.githubusercontent.com/7582457/32204116-c95ff75c-bdbd-11e7-8200-569196de3c86.png)

**Comment by piubellofelipe** [comment]
this seems to be a backend problem.
JSON response for group2014 and notificationstest:
```
{ 
    ...
total_members: 1,
...
}
```

**Comment by piubellofelipe** [comment]
@igaponov please see this

**Comment by igaponov** [comment]
Fixed:
``` bash
$ http GET https://api-dev.powerli.ne/api/v2/groups/423 "Token: $TOKEN"
HTTP/1.1 200 OK
...

{
    //...
    "total_members": 2
}
```

**Comment by piubellofelipe** [comment]
thanks, it's working.

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/31/17 - 10/31/17
Work session total: 0:08:36

Grand total: 0:08:36
