### ISSUE TITLE
Release A - UI Design of Collapsed Group Header UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#256]
We should shorten the vertical height of the group header UI including avatar is 110% height of text. Background can be white

This just looks very clunky right now
![image](https://user-images.githubusercontent.com/7582457/32239559-3cd60130-be41-11e7-8473-e7422e90e995.png)

**Comment by piubellofelipe** [comment]
@jterps08 , these changes should apply for both header types, right? I mean, right now we have a longer header and a short (the one in the pic is the short one).
here's what it'd look like only shortened and with white background:
![image](https://user-images.githubusercontent.com/18724958/32254386-90f1f882-be87-11e7-9579-141ccc342178.png)
...borders, maybe?

**Comment by jterps08** [comment]
Yes @piubellofelipe , both. ...Light grey border like the bottom tab-navigator would be perfect. Thanks

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/01/17 - 11/01/17
Work session total: 1:12:11

Grand total: 1:12:11
