### ISSUE TITLE
Release B - Critical Issues - Login/Registration

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#291]
1) New Device/Phone Number Scenario - user provides username, zip, and previous phone number. If match, backend sends e-mail link to user. If link clicked, user is able to get token after returning to app. 

2) Profile Completion (Verified flag) - Backend needs to indicate if all information has been provided (street address, birthdate, email verification (for Manual), phone verification (for FB), avatar (for Manual)... We need to expose this where there user's avatar is currently exposed so that we can add the verification badge. 

3) For SMS codes in general, we need error code provided from backend if phone number does not exist, and we need that error handled/displayed on frontend

4) When it comes time to deploy to prod, we will delete non-FB users (pending confirmation from Jesse)

5) From backend perspective, we need to make sure a) manual registration only occurs if sms code is verified, b) fb profile completion occurs only if sms code is verified, and c) manual profile completion only occurs if email link is clicked... where profile completion = user verified...

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/24/17 - 11/25/17
Work session total: 3:58:21

Grand total: 3:58:21
