### ISSUE TITLE
S2 - Comment Entry Modal & New Post/Petition Screen - @Mention Suggestion

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#32]
When @mentioning a user in the body of a post or user petition or in the comments on any item, a small pop-up displays after the user has entered @text (after the first two characters of text after the @symbol). 

If the user is an owner or manager in the group and decides to type @everyone, the app will interject and say "Are you sure you want to alert everyone in the group?" 

@everyone does not appear in the suggestions.

**Comment by jterps08** [comment]
assigning to Matheus as basic PL API-related frontend work (after #132)...

**Comment by jterps08** [comment]
@piubellofelipe 
on iOS: This function works correctly on New Posts/Petitions, but it does not work on comments
![image](https://user-images.githubusercontent.com/7582457/31644733-caa51b18-b2c5-11e7-9865-31f324694cf8.png)
on Android: Not yet tested.

For all scenarios (posts/petitions/comments), the flow should be:
1) user types in text and two characters like @12 
2) auto-completion suggest pop-up shows
3) user selects suggestion
4) text is entered (e.g. @12345)
5) pop-up disappears after selection <--- Not implemented.

Example of 5: User already selected @zxc6 from pop-up, but pop-up still shows.
![image](https://user-images.githubusercontent.com/7582457/31644768-03998a8a-b2c6-11e7-81dd-046bab128507.png)

**Comment by jterps08** [comment]
This is not resolved, but closing as it's captured in #275

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/11/17 - 10/29/17
Work session total: 5:23:27

Grand total: 5:23:27
