### ISSUE TITLE
S2 - Nav Bar & Groups List - Badge Counters

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#33]
Badge counter should appear next to the Newsfeed icon. It should also appear on each group avatar within the Group Selector (All, town, state, country, and More button) along with all groups in the Group Selector List. The badge counter represents the number of items in the Priority Zone for that item (e.g. how many items overall in All feed, or just for Save the Whales). I will explain this on Slack; the count of priority zone items is provided by the backend. 

Other badges appear on:
Notifications Feed - when there is new content since user last viewed the feed. Once viewed, badge clears. 
Announcements Feed - when there is new content since user last viewed the feed. Once viewed, badge clears.

**Comment by jterps08** [comment]
![image](https://user-images.githubusercontent.com/7582457/28977472-25f4910a-7910-11e7-9951-5986bde5e13d.png)

![image](https://user-images.githubusercontent.com/7582457/28977478-2c85cb7e-7910-11e7-9fee-ec99939f96e5.png)

**Comment by jterps08** [comment]
@igaponov given how many counters we have here, we might want to create an endpoint for just counters? not sure if you want to add that to the newsfeed or not

All counter
(town) counter
(state) counter
(country) counter
group x counter (and group y etc etc)

Right now, I'm thinking that we just use the frontend to determine if there is net-new content in Friends Feed tab and Notifications Feed tab. If user has seen content and there is no new content, no indicator. If user has not seen new content, there is an indicator (no counter, just the filled in circle)

For Messages tab, this should work similarly to Announcements tab in Ionic app where an announcement is marked as read and if there are unread announcements then the badge appears.

@igaponov  thoughts?

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-v2-user-groups, `priority_item_count` attribute

**Comment by jterps08** [comment]
@thiago-19960626 please see this if you have not yet.

**Comment by jterps08** [comment]
Opening. @igaponov please provide endpoint for All counter

**Comment by jterps08** [comment]
And can you explain difference between this https://api-dev.powerli.ne/api-doc#get--api-v2-user-groups, priority_item_count attribute and the All counter endpoint?

**Comment by igaponov** [comment]
All counter is a sum of all priority_item_count from https://api-dev.powerli.ne/api-doc#get--api-v2-user-groups

**Comment by jterps08** [comment]
It may actually make sense to do this at the same time as #135 since the solution to #135 may be background loading of Group Selector screen and, thus, the counter from the endpoint provided by Igor. Your choice.

**Comment by jterps08** [comment]
@igaponov Are we also sending the user's 'all' count with the notification payload?

**Comment by mobileDevNativeCross** [comment]
How do you imagine it? When we open app firstly get from API  https://api-dev.powerli.ne/api-doc#get--api-v2-user-groups, and https://api-dev.powerli.ne/api-doc#get--api-v2-user-statistics. And where to get notifications all, more, notifications, friends and messages badge? Also currently app always clean data before fetch new for all pages, I cannot do read functionality with this logic. And I should get count from API and then control it in app, then clean all of this and  again get count that is not changed on backend. It's really strange for me. Can it be more explained how it should work, maybe we need to rebuild logic in app before start work on this task.
