### ISSUE TITLE
S2 - Representative Profile Screen - General UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#35]
Use v2.0 screen as guide

User should see all the same information and the app should appropriately hyperlink web addresses, phone numbers, e-mails or youtube links, etc.

**Comment by piubellofelipe** [comment]
@igaponov , it seems to me that /api/representatives is coming with missing info for some objects.
I am looking at the response right now, and "Baraky Obama" doesnt come with storageId, but "Donald Trump" does.
please also check if we are using the right endpoint.
@jterps08 , can you confirm you can see the details of "Donald Trump", but not "Baraky Obama"?
