### ISSUE TITLE
S2 - Notifications Feed - General UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#37]
See the "You" tab from the Social Activity Feed in v2.0
React-ify this screen please and do your best to make it more readable and user-friendly :-) 

The primary activities that this feed shows are:

- John Smith requested to follow you (this should include quick ability to approve/reject, and follow-back). These should be listed first in their own section.
- John Smith commented on your post
- John Smith voted on your post
- John Smith invited you to a Group with quick ability to Join/Leave the group.

The Notifications Feed will actually display all the social notifications relevant to the logged-in user including follow requests, group invites, who's commented on their authored content, and who's upvoted/downvoted/signed their content. This is currently the information displayed in the “You” tab of the v2.0 Social Activity Feed (group invites are currently displayed in v2.0 on Announcements feed)/ For all of the follow requests that appear in the Notifications Feed, it will be easy to approve/reject and optionally follow someone back from that feed. Or join / ignore a group invite. The Notifications Feed icon will feature a badge counter that returns a count of all of the new items since the user last viewed the feed. It disappears when the feed is viewed. *All activities in the Notifications hyperlink to the corresponding Item Detail Screen.*

![image](https://user-images.githubusercontent.com/7582457/30999004-3acbba3e-a4a0-11e7-8720-22f5f113dee2.png)

**Comment by jterps08** [comment]
After #13

**Comment by jterps08** [comment]
Related: https://github.com/PowerlineApp/powerline-server/issues/617#event-1283346802

@igaponov I will need you to explain this to Felipe when it's time to work on this item. I am not sure what remaining action, if any, exists on Frontend for this.

**Comment by igaponov** [comment]
After user approved/reject a follow request according social activity will be deleted automatically, so frontend don't need to take care about buttons (Approve/Ignore) in a newsfeed. It works when a button in push message is clicked as well.

**Comment by jterps08** [comment]
To confirm - there is no extra action needed on frontend, right @igaponov ?

**Comment by igaponov** [comment]
@jterps08 yes.

**Comment by jterps08** [comment]
Closing this for now. Assuming Join/Ignore and Follow/Ignore buttons work.
