### ISSUE TITLE
S3 - Search Results - General UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#43]
See v2.0 for approximation.

The backend search function supports searching for people, groups, and hashtags. The search results screen will be different depending on the parent search bar.

- Search bar on the main screen - shows results for people, groups, and hashtags, sectioned accordingly. People and groups will show avatars and names. Hashtag results will show actual posts (using Standard Item Detail container)
- Search bar on the Groups screen - shows results for groups
- Search bar on the Influences screen - shows results for people

I may need to come back and add more detail here, but you may approximate this the best that you can.

**Comment by jterps08** [comment]
Adding context here for Search Bar on Main Screen... 

When user enters text into Search Bar on Main/Home Screen, the search results screen appears after a couple seconds (or if user hits Enter)... Search Results screen has 3 tabs: Groups (default), People, #Hashtags. So, user actually sees results for Groups first, but when user taps on People or Hashtags tabs, search results should show People results or Hashtag results. 

It is important that the first results be for Groups

**Comment by jterps08** [comment]
This is still open because:
1) When user enters text into search bar, it should open search results screen (from burger menu) with results for Group tab showing... Right now, user enters text and nothing happens. See screenshot.
![image](https://user-images.githubusercontent.com/7582457/31478246-01035db0-aedd-11e7-8b4a-1b3160198830.png)


2) The Hashtags tab is not connected yet. It will use [see Igor] endpoint and results should be displayed using same style as newsfeed. This probably needs to wait until after Newsfeed has been consolidated into one place.
![image](https://user-images.githubusercontent.com/7582457/31478249-05a2bf3c-aedd-11e7-9cfe-3259c6f5f97a.png)

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#get--api-v2-activities
Use `hash_tag` query param to filter activities.
