### ISSUE TITLE
S2 - User Profile Screen - General UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#44]
See v2.0 for approximation.

When viewing another user, it should be easy to follow or unfollow that user from the user profile screen.
If the user is an approved follower, additional information will display. 

Information is as follows:

**For public (all users)**
It should show Tagline, Bio, and Country fields... and authored posts in shared public communities (User A follows User B. User A and B live in California and New Jersey, but both live in USA. User A can see User B's posts in USA group, but cannot see posts in New Jersey group).

**For approved followers**, it should show Tagline, Bio, **Issues**, **State**, and Country fields... and authored posts in shared public communities **and authors posts in shared groups with the user**.

Date of Birth should not be shown. City should not be shown.

**Comment by jterps08** [comment]
![image](https://cloud.githubusercontent.com/assets/7582457/26804091/c4216fcc-4a14-11e7-83f8-79c6f9aeb787.png)

**Comment by jterps08** [comment]
this is incomplete @thiago-19960626

**Comment by jterps08** [comment]
@thiago-19960626 you should not be closing issues. You should change add the label "Ready for Retest" and I will review it and determine if it should be closed.

**Comment by thiago-19960626** [comment]
make sense
