### ISSUE TITLE
S0 - Login Screen - Forgot Password

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#5]
User should have the ability to click a link if he has forgotten password. User is prompted for e-mail address. When the user submits his e-mail address, a visual indicator informs him that "A link to reset your password has been sent to your e-mail address."

https://api-dev.powerli.ne/api-doc#post--api-secure-forgot-password

**Comment by jterps08** [comment]
This link should be moved underneath "Sign up with Email"

**Comment by awis0330** [comment]
Okay
Will move it underneath `Sign Up` button and create PR again
