### ISSUE TITLE
S2 - Post Analytics Screen

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#64]
See provided UI. This screen is accessed from "Analytics" button on the Item Detail Screen. 

There are several views that the user can choose from the filter. The default view displays the specific logged-in user's elected leaders and the upvote/downvote statistics information for each of those leaders. The app allows the user to show Upvote stats or Downvote stats (percent and count). The endpoint provides both per each elected leader. 

1. My Elected Leaders View - Upvote/Downvote stats for each of the user's linked elected leaders
2. Authors Elected Leaders View - Upvote/Downvote stats for each of the post author's linked elected leaders
3. Most Popular Elected Leaders View - Upvote/Downvote stats for the most popular elected leaders linked to the post (top 15)
4. Custom Lookup - Returns the stats for a provided elected leader

The return from the backend provides the leader, their title, and the related stats for that post. (e.g. Donald Trump, President, 90% Upvote, 200 Upvotes, 10% Downvote, 20 Downvotes). The app displays the Upvote stats or the Downvote stats depending on whether the Upvote filter is selected or the Downvote filter is selected.

Backend endpoints for this will be provided by @igaponov once ready. (Igor, let's talk on Slack)

**Comment by jterps08** [comment]
https://github.com/PowerlineApp/powerline-mobile/issues/600

**Comment by jterps08** [comment]
1 is done (above)... 2 and 3 are next.

**Comment by matheusrezende** [comment]
via Hubstaff
User: Matheus Rezende Figueira

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 11/02/17 - 11/06/17
Work session total: 11:28:07

Grand total: 11:28:07
