### ISSUE TITLE
S0 - Home Screen - Basic UI

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#7]
See provided v3.0 PSDs for Home Screen / Newsfeed design

Includes the Menu button 
- Menu is identical to v2.0 (all buttons inactive, except Logout)
- User should be able to logout with Logout button and return to Login screen

Includes the Group Selector Shortcuts 
- The All, Town, State, and Country buttons - should display the user's specific town, state, and country names. You will need to talk to @igapanov on how to get these or see how v2.0 does it
- The "More" Button (inactive) links to the group list of all of the user's groups as per mockup (not expected in Sprint 0, but https://api-dev.powerli.ne/api-doc#get--api-v2-groups

Includes the Navigation Bar with each tab
- No content expected in any tab, but user should be able to change tabs and it should be visually clear which tab is currently selected.
- The newsfeed tab is always the default tab.
- The badge counters on each tab do not need to be displayed. I will explain them in a later sprint.

![image](https://cloud.githubusercontent.com/assets/7582457/25544773/00ccc100-2c2a-11e7-924c-569cd3686104.png)

(For Vision/information only): A general overall description of the Newfeed / Home Screen:
The Main Newsfeed is used to display the All feed and any groups that the user selects from the Group Selector modal. By default, the main newsfeed displays the All feed. The main newsfeed button will have a badge counter indicating all items in the priority zone. The counter does not clear until the priority zone is clear (handled by the backend). All content that appears in the Main Newsfeed follows the format of the Standard Item Container (explained below). Any item that is in the priority zone has a marking/indicator that appears in the Standard Item Container. If the All feed has 5 items in the priority zone counter, then the first five items in the Newsfeed will each of their own priority zone marking (e.g. lightning icon)

The backend programmatically determines the newsfeed sorting order. Typically, priority zone items (unread discussions/petitions, unanswered polls/fundraisers/events/boosted-posts/boosted-user-petitions) come first followed by non-priority zone content, followed by expired content. The priority zone is how Powerline helps make sure important content is always at the top of the user’s feed for action. The badge counters for all of the feeds are a count of the priority zone items in that feed, and the counter does not go away until the items are read or answered, depending on the item.

**Comment by jterps08** [comment]
I can provide you with the Powerline "P" logo which can be used on the All button. 

Please update the nav bar color scheme as we discussed to match the provided UI

**Comment by awis0330** [comment]
I'd like you to choose the icon in ionicons but okay, please give the icon.

Already updated the nav bar color and you can check it in next beta build.

Regarding menu layout, It is possible but let me handle it after Sprint 1 if it works.
