### ISSUE TITLE
S3 - New Post Screen - Crossposting to Twitter or Facebook

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#74]
By leveraging this tool https://github.com/doefler/react-native-social-share

Allows the user to check a box on the Post/Petition screen to share the text to Twitter **or** Facebook. After the user successfully posts the item on Powerline, the pop-up screen shows up for Twitter or Facebook depending on what the user selected. The body of the post is filled into the pop-up.

This includes the text-as-image concept as discussed on Slack.

**Comment by igaponov** [comment]
https://api-dev.powerli.ne/api-doc#post--api-v2.2-groups-{group}-posts
https://api-dev.powerli.ne/api-doc#post--api-v2.2-groups-{group}-user-petitions
Attribute `facebook_thumbnail` contains an url.

**Comment by jterps08** [comment]
Thanks @igaponov I think we need it on the Get Activities by ID endpoint, too

**Comment by piubellofelipe** [comment]
via Hubstaff
User: Felipe Piubello

Project: Powerline React Native - https://app.hubstaff.com/projects/264175
Date Range: 10/22/17 - 10/27/17
Work session total: 10:16:22

Grand total: 10:16:22
