### ISSUE TITLE
Sprint 0 Fix - New Item Modal Labeling & Icons

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#84]
Remove "Create" from each of the labels in the New Item Modal. Use correct icons provided in Ionicons reference #83 

![image](https://user-images.githubusercontent.com/7582457/27039673-92ea3144-4f5c-11e7-8ff1-2c9b321e1af5.png)

**Comment by awis0330** [comment]
I can't find Piggy Bank icon for New Fundraiser.
Also, the icon image I found in ionic app is unavailable to use in RN app.

**Comment by jterps08** [comment]
Can you extract it from here or no? https://drive.google.com/open?id=0B2Loy21ehREyUFVwaDBwVFVWM1E

**Comment by jterps08** [comment]
If too hard or too much effort, let's just delay it until later
