### ISSUE TITLE
S0 - Home Screen - Group Selector Menu

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#9]
When the user taps the "More" button, a ListView appears with all of the user's groups. The first three items are the user's town, state/province, and country groups. All other groups appear alphabetically. 
Each row of the group selector shows the group avatar, the group name, and a little gear icon (not shown in provided mockup). 

https://api-dev.powerli.ne/api-doc#get--api-v2-groups

These will all be non-functional for now.

The below image shows the **UX flow**. User taps on "More button". Group list displays. User selects group. Group feed loads in the Newsfeed tab. 

![image](https://cloud.githubusercontent.com/assets/7582457/25584797/7a315212-2e65-11e7-8d17-5cf783f2ff46.png)

Actual Group Selector Mockup - Only shows the user's joined groups. Should also show the user's town, state, and country groups e.g. Hoboken, New Jersey, United States of America
![group selector](https://cloud.githubusercontent.com/assets/7582457/26016515/6716d130-3733-11e7-801d-b65c56709380.jpg)

**Comment by jterps08** [comment]
On the main screen, the All, Town, State, Country, and More buttons should be tappable - including their labels. Currently user needs to tap on circles. Labels should be tappable as well. 

When data is loaded for the user's groups, if the user is linked to "Hoboken", "New Jersey", "United States" groups then those will appear in the label, not "town", "state", or "Country"

**Comment by awis0330** [comment]
I will make labels touchable as well and create another PR.
Getting user profile will be integrated in issue #13.
