### ISSUE TITLE
Sprint 1 Fix - General Layout / Alignment Fix

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#92]
Attachments are centered in the Standard Item Container, but the Left side of an attachment does not align with the author name, group name, title (if applicable), and text body.

I propose that we reduce the space between the left-border of viewport and the left border of the avatar. I also propose that we reduce the space between the avatar and the author name. If we do this, we can move 
Author Name
Group name
Title (if applicable)
Text Body

We can move these to the left so that they align with a provided attachment. 

![image](https://user-images.githubusercontent.com/7582457/27048326-4f6b048a-4f79-11e7-87bb-8537a9bc0c93.png)

**Comment by awis0330** [comment]
I can make its looking perfect on one screen(e.g iPhone 5 or whatever), but hard to be perfect on every screen in short time. Let me move forward with other issues and come back to this issue later.
