### ISSUE TITLE
Sprint 1 Fix - PetitionButton Rules

### ISSUE THREAD

**Issue by jterps08** [PowerlineApp/powerline-rn#93]
As defined in Issue #13 , a Petition should show a Sign button, not Upvote Downvote buttons

![image](https://user-images.githubusercontent.com/7582457/27048355-67d8add8-4f79-11e7-9b50-239b7fcdfb94.png)

**Comment by awis0330** [comment]
![screen shot 2017-06-16 at 9 22 18 pm](https://user-images.githubusercontent.com/7454966/27228386-f8a243fc-52d9-11e7-9dec-87c05d341bf4.png)

**Comment by awis0330** [comment]
It is already showing. But icon is not determined yet.

**Comment by jterps08** [comment]
Okay - just make sure that Sign and Reply are left-aligned. Not right-aligned please.

**Comment by jterps08** [comment]
@awis0330 you can use ion-checkmark-circled from ionicons for the sign button icon
